Auditory and otorhinolaryngologic:
- auditory system disorder
- otorhinolaryngologic disease
Breast:
- breast disorder
Cancer and benign tumors:
- cancer or benign tumor
Cardiovascular:
- cardiovascular disorder
Connective tissue:
- connective tissue disorder
Developmental, congenital, and perinatal:
- disorder of development or morphogenesis
- obstetric disorder
- perinatal disease
Digestive and oral:
- digestive system disorder
- mouth disorder
Endocrine:
- endocrine system disorder
Extrinsic, toxic, and occupational:
- iatrogenic disease
- occupational disorder
- poisoning
- radiation-induced disorder
Genetic and genomic:
- disease of genetic or genomic mechanism
Hematologic:
- hematologic disorder
Idiopathic:
- idiopathic disease
Immune:
- immune system disorder
Infectious and post-infectious:
- infectious disease
- post-infectious disorder
Inflammatory:
- inflammatory disease
Integumentary:
- integumentary system disorder
Metabolic and nutritional:
- metabolic disease
- mitochondrial disease
- nutritional disorder
Musculoskeletal:
- musculoskeletal system disorder
Nervous system:
- nervous system disorder
Psychiatric and sleep:
- psychiatric disorder
- sleep disorder
Reproductive:
- reproductive system disorder
Respiratory:
- respiratory system disorder
Syndromic:
- syndromic disease
Ulcer disease:
- ulcer disease
Urinary:
- urinary system disorder
Visual system:
- disorder of visual system
